### ISSUE TITLE
No guidance for user with JS turned off

### ISSUE THREAD

**Issue by dengeist** [jhwheeler/simple-spirit#3]
If someone tries to visit Simple Spirit with JavaScript off, they see a blank white page. Consider implementing an explanation of this error, so the user knows *why* this problem happens and how to fix it.

Style this warning just like the rest of your app so that it fits in with the app itself.

**Comment by jhwheeler** [comment]
Great idea, thank you - I'll add this!

**Comment by jhwheeler** [comment]
Fixed!
